### createPost
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "My First Post",
  "content": "This is the content of the first post.",
  "sender": "User1"
}

### Get All Posts
GET http://localhost:3000/api/posts

### Get a Post by ID
GET http://localhost:3000/api/posts/6776b6e1b9f5af012a469cbc

### Get Posts by Sender
GET http://localhost:3000/api/posts?sender=User1

### Update a Post
PUT http://localhost:3000/api/posts/6776b6e1b9f5af012a469cbc
Content-Type: application/json

{
  "title": "Updated Post",
  "content": "This is the updated content."
}

### Create Comment
POST http://localhost:3000/api/posts/6776b6e1b9f5af012a469cbc/comments
Content-Type: application/json

{
  "content": "This is a comment on the post.",
  "sender": "User2"
}

### Get Comment By Id
GET http://localhost:3000/api/posts/6776b6e1b9f5af012a469cbc/comments/6776b6e1b9f5af012a469cbd

### Update Comment
PUT http://localhost:3000/api/posts/6776b6e1b9f5af012a469cbc/comments/6776b6e1b9f5af012a469cbd
Content-Type: application/json

{
  "content": "This is the updated comment.",
  "sender": "User2",
  "postId": "6776b6e1b9f5af012a469cbc"
}

### Delete Comment
DELETE http://localhost:3000/api/posts/6776b6e1b9f5af012a469cbc/comments/6776b6e1b9f5af012a469cbd

### Get Comments by Post Id
GET http://localhost:3000/api/posts/6776b6e1b9f5af012a469cbc/comments

