### createPost
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "My First Post",
  "content": "This is the content of the first post.",
  "sender": "User1"
}

### Get All Posts
GET http://localhost:3000/api/posts

### Get a Post by ID
GET http://localhost:3000/api/posts/6776ca6016747645178c199e

### Get Posts by Sender
GET http://localhost:3000/api/posts?sender=User1

### Update a Post
PUT http://localhost:3000/api/posts/6776ca6016747645178c199e
Content-Type: application/json

{
  "title": "Updated Post",
  "content": "This is the updated content."
}

### Create Comment
POST http://localhost:3000/api/comments
Content-Type: application/json

{
  "content": "This is a comment on the post.",
  "sender": "User2",
  "postId": "6776ca6016747645178c199e"
}

### Get Comment By Id
GET http://localhost:3000/api/comments/6776cb39096ef8f8bf5a0787

### Update Comment
PUT http://localhost:3000/api/comments/6776cb39096ef8f8bf5a0787
Content-Type: application/json

{
  "content": "This is the updated comment.",
  "sender": "User2",
  "postId": "6776ca6016747645178c199e"
}

### Delete Comment
DELETE http://localhost:3000/api/comments/6776b6e1b9f5af012a469cbc

### Get Comments by Post Id
GET http://localhost:3000/api/comments/post/6776b6e1b9f5af012a469cbc

